"""udate

Revision ID: 08004a8a45c3
Revises: e9a3b1b2861a
Create Date: 2022-10-18 22:01:50.255056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08004a8a45c3'
down_revision = 'e9a3b1b2861a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
