"""all table autogenrate

Revision ID: 6a08859d0147
Revises: a46ab5bac2fa
Create Date: 2022-10-16 16:20:41.656438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a08859d0147'
down_revision = 'a46ab5bac2fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts1.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.add_column('posts1', sa.Column('content', sa.String(), nullable=False))
    op.add_column('posts1', sa.Column('publish', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('posts1', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts1', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts1', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts1', type_='foreignkey')
    op.drop_column('posts1', 'owner_id')
    op.drop_column('posts1', 'created_at')
    op.drop_column('posts1', 'publish')
    op.drop_column('posts1', 'content')
    op.drop_table('votes')
    op.drop_table('users')
    # ### end Alembic commands ###
